import type { AppRouteModule } from '/@/router/types';

const pagesIndex: AppRouteModule = {
	path: '/pages',
	name: 'pagesIndex',
	component: () => import('/@/layout/routerView/parent.vue'),
	redirect: '/pages/filtering',
	meta: {
		orderNo: 6,
		title: 'message.router.pagesIndex',
		isLink: '',
		isHide: false,
		isKeepAlive: true,
		isAffix: false,
		isIframe: false,
		roles: ['admin', 'common'],
		icon: 'iconfont icon-fuzhiyemian',
	},
	children: [
		{
			path: '/pages/filtering',
			name: 'pagesFiltering',
			component: () => import('/@/views/pages/filtering/index.vue'),
			meta: {
				title: 'message.router.pagesFiltering',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'ele-Sell',
			},
			/**
			 * 注意此处详情写法：
			 * 1、嵌套进父级里时，面包屑显示为：首页/页面/过滤筛选组件/过滤筛选组件详情
			 * 2、不嵌套进父级时，面包屑显示为：首页/页面/过滤筛选组件/过滤筛选组件详情
			 * 3、想要父级不高亮，面包屑显示为：首页/页面/过滤筛选组件详情，设置路径为：/pages/filteringDetails
			 */
			children: [
				{
					path: '/pages/filtering/details',
					name: 'pagesFilteringDetails',
					component: () => import('/@/views/pages/filtering/details.vue'),
					meta: {
						title: 'message.router.pagesFilteringDetails',
						isLink: '',
						isHide: true,
						isKeepAlive: false,
						isAffix: false,
						isIframe: false,
						roles: ['admin', 'common'],
						icon: 'ele-Sunny',
					},
				},
			],
		},
		{
			path: '/pages/filtering/details1',
			name: 'pagesFilteringDetails1',
			component: () => import('/@/views/pages/filtering/details1.vue'),
			meta: {
				title: 'message.router.pagesFilteringDetails1',
				isLink: '',
				isHide: true,
				isKeepAlive: false,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'ele-Sunny',
			},
		},
		{
			path: '/pages/iocnfont',
			name: 'pagesIocnfont',
			component: () => import('/@/views/pages/iocnfont/index.vue'),
			meta: {
				title: 'message.router.pagesIocnfont',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'ele-Present',
			},
		},
		{
			path: '/pages/element',
			name: 'pagesElement',
			component: () => import('/@/views/pages/element/index.vue'),
			meta: {
				title: 'message.router.pagesElement',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'ele-Eleme',
			},
		},
		{
			path: '/pages/awesome',
			name: 'pagesAwesome',
			component: () => import('/@/views/pages/awesome/index.vue'),
			meta: {
				title: 'message.router.pagesAwesome',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'ele-SetUp',
			},
		},
		{
			path: '/pages/formAdapt',
			name: 'pagesFormAdapt',
			component: () => import('/@/views/pages/formAdapt/index.vue'),
			meta: {
				title: 'message.router.pagesFormAdapt',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-biaodan',
			},
		},
		{
			path: '/pages/tableRules',
			name: 'pagesTableRules',
			component: () => import('/@/views/pages/tableRules/index.vue'),
			meta: {
				title: 'message.router.pagesTableRules',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-jiliandongxuanzeqi',
			},
		},
		{
			path: '/pages/formI18n',
			name: 'pagesFormI18n',
			component: () => import('/@/views/pages/formI18n/index.vue'),
			meta: {
				title: 'message.router.pagesFormI18n',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-diqiu',
			},
		},
		{
			path: '/pages/formRules',
			name: 'pagesFormRules',
			component: () => import('/@/views/pages/formRules/index.vue'),
			meta: {
				title: 'message.router.pagesFormRules',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-shuxing',
			},
		},
		{
			path: '/pages/listAdapt',
			name: 'pagesListAdapt',
			component: () => import('/@/views/pages/listAdapt/index.vue'),
			meta: {
				title: 'message.router.pagesListAdapt',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-chazhaobiaodanliebiao',
			},
		},
		{
			path: '/pages/waterfall',
			name: 'pagesWaterfall',
			component: () => import('/@/views/pages/waterfall/index.vue'),
			meta: {
				title: 'message.router.pagesWaterfall',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-zidingyibuju',
			},
		},
		{
			path: '/pages/steps',
			name: 'pagesSteps',
			component: () => import('/@/views/pages/steps/index.vue'),
			meta: {
				title: 'message.router.pagesSteps',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-step',
			},
		},
		{
			path: '/pages/preview',
			name: 'pagesPreview',
			component: () => import('/@/views/pages/preview/index.vue'),
			meta: {
				title: 'message.router.pagesPreview',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-15tupianyulan',
			},
		},
		{
			path: '/pages/waves',
			name: 'pagesWaves',
			component: () => import('/@/views/pages/waves/index.vue'),
			meta: {
				title: 'message.router.pagesWaves',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-bolangneng',
			},
		},
		{
			path: '/pages/tree',
			name: 'pagesTree',
			component: () => import('/@/views/pages/tree/index.vue'),
			meta: {
				title: 'message.router.pagesTree',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'iconfont icon-shuxingtu',
			},
		},
		{
			path: '/pages/drag',
			name: 'pagesDrag',
			component: () => import('/@/views/pages/drag/index.vue'),
			meta: {
				title: 'message.router.pagesDrag',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin', 'common'],
				icon: 'ele-Pointer',
			},
		},
		{
			path: '/pages/lazyImg',
			name: 'pagesLazyImg',
			component: () => import('/@/views/pages/lazyImg/index.vue'),
			meta: {
				title: 'message.router.pagesLazyImg',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin'],
				icon: 'ele-PictureFilled',
			},
		},
		{
			path: '/pages/dynamicForm',
			name: 'pagesDynamicForm',
			component: () => import('/@/views/pages/dynamicForm/index.vue'),
			meta: {
				title: 'message.router.pagesDynamicForm',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin'],
				icon: 'iconfont icon-wenducanshu-05',
			},
		},
		{
			path: '/pages/workflow',
			name: 'pagesWorkflow',
			component: () => import('/@/views/pages/workflow/index.vue'),
			meta: {
				title: 'message.router.pagesWorkflow',
				isLink: '',
				isHide: false,
				isKeepAlive: true,
				isAffix: false,
				isIframe: false,
				roles: ['admin'],
				icon: 'ele-Connection',
			},
		},
	],
};

export default pagesIndex;
